# Generated by Django 4.2.1 on 2023-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_name_category_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='listing',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
